#!/usr/bin/env python3
"""boards -> animatic, an on-request reference build (MASTER-PLAN-V2 D8).

UPDATED 2026-08-29 (Phase 9, D8): under V1 this module's docstring called the
animatic "the missing spine" and "THIS is the artifact that gets approved" -
that was true under V1, where the animatic was a gated stage the service
auto-produced from boards. **V2 demotes it.** The approved PANEL is the spine
now (see MASTER-PLAN-V2.md section 1 and D8); the animatic is a deferred,
on-request REFERENCE artifact only, with NO approval gate of its own. Nothing
in this file changed to make that true except who/what calls it - see
genvideo_service.py's PHASE 9 block for the watcher change. This tool's own
behaviour (board generation, the timed cut, subtitles, the episode stitch) is
unchanged and still fully supported as a CLI.

What this adds, all through ShotGrid state:

  BOARD  one still per shot at board fidelity, published as a Version on the
         BRD pipeline Step, stage=board. Cheap: a single frame, so an episode of
         boards costs minutes, not hours. Still auto-generated by the service
         when a shot reaches sg_stage=board - this part is unchanged by D8.

  ANIMATIC  those boards held for each shot's real duration and concatenated in
         cut order, with burnt-in shot code and timecode, published as a Version
         on the Sequence. A timing REFERENCE, not a reviewed/approved gate -
         nothing downstream waits on its status.

Triggers, per Geoff: ShotGrid state only, and (per D8) the animatic cut is
never automatic:
    Shot.sg_stage = board                       -> that shot's board is
                                                     generated (service-driven,
                                                     unchanged)
    Sequence.sg_gen_status = animatic_requested  -> that sequence's animatic
                                                     is cut, ON REQUEST ONLY
                                                     (service-driven; see
                                                     genvideo_service.py)

The service calls --boards and --animatic (the latter only on explicit
request, never on a board approval or a stage read). --episode has NO
service-side trigger as of Phase 9 - there is no ShotGrid entity that
represents "the whole episode" for a request to live on, so run it by hand:
    C:\\genvideo\\venv\\Scripts\\python.exe build\\tools\\animatic.py --episode
"""
import argparse
import os
import re
import subprocess
import sys
import time
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sg_provenance as PROV                                   # noqa: E402
import sg_publish as PUB                                       # noqa: E402
import dialogue_guard as DG                                    # noqa: E402  D15, invariant 11
import episode_context as EPCTX                                # noqa: E402

PY = sys.executable
ROOT = os.environ.get("GENVIDEO_ROOT", os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# E0 FIX (docs/METHOD.md): was os.path.join(ROOT, "build", "tools"),
# which only feeds WRAPPER below -- self-relative now so the ComfyUI wrapper
# path resolves inside whichever release actually deployed this file.
TOOLS = os.path.dirname(os.path.abspath(__file__))
TESTS = os.path.join(ROOT, "build", "tests")
WRAPPER = os.path.join(TOOLS, "comfyui", "comfyui_execute.py")
TPL_T2V = os.path.join(ROOT, "workflows", "wan22_ti2v_5b_t2v.api.json")
TPL_I2V = os.path.join(ROOT, "workflows", "wan22_ti2v_5b_i2v.api.json")
OUT_COMFY = r"C:\ComfyUI_windows_portable\ComfyUI\output"
IN_COMFY = r"C:\ComfyUI_windows_portable\ComfyUI\input"
BOARDS = os.path.join(ROOT, "output", "boards")
ANIMATICS = os.path.join(ROOT, "output", "animatics")
COMFY_EXE = r"C:\ComfyUI_windows_portable\python_embeded\python.exe"
COMFY_MAIN = r"C:\ComfyUI_windows_portable\ComfyUI\main.py"
FFMPEG = os.environ.get("FFMPEG", "ffmpeg")
FFPROBE = os.environ.get("FFPROBE", "ffprobe")
FONT = r"C\:/Windows/Fonts/consola.ttf"
PROJ = {"type": "Project", "id": 9999}
EP = EPCTX.resolve_episode()
BOARD_STEP = "BRD"


def sg_connect():
    import pm_backend_shotgrid as PMB
    return PMB.get_backend()


def log(m):
    print("[animatic] %s" % m, flush=True)


def comfy_up():
    try:
        urllib.request.urlopen("http://127.0.0.1:8188/system_stats", timeout=3)
        return True
    except Exception:
        return False


def comfy_start():
    if comfy_up():
        return True
    g = subprocess.run([PY, os.path.join(TESTS, "gpu_guard.py")], capture_output=True, text=True)
    if g.returncode != 0:
        log("gpu guard: %s" % g.stdout.strip())
        return False
    os.makedirs(BOARDS, exist_ok=True)
    subprocess.Popen([COMFY_EXE, "-s", COMFY_MAIN, "--windows-standalone-build",
                      "--listen", "127.0.0.1", "--port", "8188"],
                     stdout=open(os.path.join(BOARDS, "comfy.log"), "a"),
                     stderr=subprocess.STDOUT, cwd=r"C:\ComfyUI_windows_portable")
    for _ in range(180):
        time.sleep(0.5)
        if comfy_up():
            return True
    return False


def comfy_stop():
    # TEARDOWN IS OFF BY DEFAULT (Geoff, 2026-09-05). The rule existed because this
    # project began as "how to get ComfyUI renders onto the Royal Render farm", where
    # the box was shared with other jobs and an idle ComfyUI held VRAM somebody else
    # needed. That is not what we do now and nothing else uses this machine, so paying
    # a full model reload per render buys nothing.
    #
    # Set GENVIDEO_TEARDOWN_COMFY=1 to restore the old behaviour the moment this box is
    # shared again. It logs on every skip: a behaviour change that goes quiet is how a
    # shared GPU gets held hostage without anyone noticing.
    if os.environ.get("GENVIDEO_TEARDOWN_COMFY", "") != "1":
        log("teardown: SKIPPED, ComfyUI left running "
            "(set GENVIDEO_TEARDOWN_COMFY=1 to restore teardown)")
        return
    subprocess.run(["powershell", "-NoProfile", "-Command",
                    "Get-NetTCPConnection -State Listen -LocalPort 8188 -EA SilentlyContinue | "
                    "ForEach-Object { Stop-Process -Id $_.OwningProcess -Force -EA SilentlyContinue }"])
    time.sleep(4)
    v = subprocess.run([PY, os.path.join(TESTS, "teardown_verify.py")],
                       capture_output=True, text=True)
    log("teardown: %s" % ("VERIFIED" if v.returncode == 0 else "NOT CLEAN"))


def sequence_style(sg, shot):
    seq = shot.get("sg_sequence")
    if not seq:
        return "", "", ""
    s = sg.find_one("Sequence", [["id", "is", seq["id"]]],
                    ["sg_style_prefix", "sg_style_suffix", "sg_style_negative"])
    if not s:
        return "", "", ""
    return (s.get("sg_style_prefix") or "", s.get("sg_style_suffix") or "",
            s.get("sg_style_negative") or "")


def fragments(sg, shot):
    links = shot.get("assets") or []
    if not links:
        return ""
    rows = sg.find("Asset", [["id", "in", [a["id"] for a in links]]],
                   ["code", "sg_prompt_fragment", "sg_fragment_order"])
    rows.sort(key=lambda r: (r.get("sg_fragment_order") or 999, r.get("code") or ""))
    return ", ".join(r["sg_prompt_fragment"].strip()
                     for r in rows if r.get("sg_prompt_fragment"))


# --- D6_COMPONENTS ------------------------------------------------------------
# classify_assets() lives in sg_provenance.py (invariant 11's "one place, import
# it, never copy" spirit) - use PROV.classify_assets(sg, shot) directly.


def still_for_shot(shot, sg=None):
    """-> the still to hold for this shot's duration, or None.

    THE APPROVED PANEL FIRST, then the board. This module's OWN docstring
    already says so -- "V2 demotes it. The approved PANEL is the spine" -- and
    the code went on requiring a board file that V2 stopped producing. Measured
    2026-09-05: SHOW01 carries 133 panel Versions and ZERO boards, so
    requesting an animatic on a fully approved sequence refused with "2 shot(s)
    have no board" on shots that had both an approved panel and a finished
    video. A stage unreachable for the only episode in production.

    The board path is kept, not replaced: an episode that does have boards
    still animatics from them, and boards remain the cheaper artefact for a
    sequence whose panels are not approved yet. Preference, not substitution.
    """
    # sg_approved_panel is an entity LINK ({type,id,name}), NOT a path -- I
    # read it as one and it silently returned None for every shot, which would
    # have looked exactly like "no panel approved". Resolve the Version and ask
    # it where its media is.
    link = shot.get("sg_approved_panel") or {}
    if sg is not None and link.get("id"):
        try:
            v = sg.find_one("Version", [["id", "is", link["id"]]],
                            ["sg_path_to_movie"])
        except Exception:                                         # noqa: BLE001
            v = None
        ap = (v or {}).get("sg_path_to_movie")
        if ap and os.path.isfile(ap):
            return ap
    board = os.path.join(BOARDS, "%s_BRD_v001.png" % shot["code"])
    return board if os.path.exists(board) else None


def board_task(sg, shot):
    t = sg.find_one("Task", [["entity", "is", {"type": "Shot", "id": shot["id"]}],
                             ["step.Step.short_name", "is", BOARD_STEP]], ["content"])
    if t:
        return t
    step = sg.find_one("Step", [["short_name", "is", BOARD_STEP],
                                ["entity_type", "is", "Shot"]], ["code"])
    if step is None:
        step = sg.create("Step", {"short_name": BOARD_STEP, "code": "Board",
                                  "entity_type": "Shot"})
    return sg.create("Task", {"project": PROJ, "entity": {"type": "Shot", "id": shot["id"]},
                              "step": step, "content": "Board"})


def make_board(sg, shot):
    """One still per shot, at board fidelity. Deliberately the SAME composition
    path as video so the board is a true preview, not a different picture."""
    # D15: same defense-in-depth choke point as genvideo_worker.generate() --
    # sg_gen_prompt is not normally script-beat-formatted, but strip here
    # anyway, at the point this text becomes a GPU call, rather than trust
    # every upstream writer (invariant 11).
    prompt = DG.strip_dialogue_for_prompt(shot.get("sg_gen_prompt") or "").strip()
    if not prompt:
        return None, "sg_gen_prompt is empty"
    pre, suf, neg = sequence_style(sg, shot)
    frag = fragments(sg, shot)
    if frag:
        prompt = prompt.rstrip(" ,.") + ", " + frag
    if pre and pre.strip().lower() not in prompt.lower():
        prompt = pre.strip() + " " + prompt
    if suf and suf.strip().lower() not in prompt.lower():
        prompt = prompt.rstrip(" ,.") + suf
    prompt = " ".join(prompt.split())
    negative = neg or "blurry, distorted, watermark, text"

    size = (shot.get("sg_gen_size_wxh") or "768x432").lower().split("x")
    prefix = "brd_%s" % shot["code"].lower()
    seed = int(shot.get("sg_gen_seed") or 1000)
    cmd = [PY, WRAPPER, "0", "0", "1", "--workflow", TPL_T2V,
           "--comfy-output-dir", OUT_COMFY, "--verify-mode", "disk",
           "--output-prefix", prefix, "--seed-base", str(seed),
           "--expect-outputs", "1", "--timeout", "900",
           "--set", "prompt=%s" % prompt, "--set", "negative_prompt=%s" % negative,
           "--set", "width=%s" % size[0], "--set", "height=%s" % size[1],
           "--set", "length=1", "--set", "steps=%d" % int(shot.get("sg_gen_steps") or 10),
           "--set", "cfg=%s" % (shot.get("sg_gen_cfg") or 5.0)]
    t0 = time.time()
    r = subprocess.run(cmd, capture_output=True, text=True)
    if "PASS:" not in r.stdout:
        return None, "board generation failed: %s" % r.stdout[-300:]
    os.makedirs(BOARDS, exist_ok=True)
    src = os.path.join(OUT_COMFY, "%s_w000_00001_.png" % prefix)
    dst = os.path.join(BOARDS, "%s_BRD_v001.png" % shot["code"])
    import shutil
    shutil.copyfile(src, dst)
    return (dst, prompt, negative, round(time.time() - t0, 1)), None


def publish_board(sg, shot, dst, prompt, negative, took):
    """Publishes through sg_publish.publish_version() (the one contract, per
    docs/METHOD.md) instead of a bare sg.create() +
    sg.upload_thumbnail(). THE FIX: this used to call ONLY upload_thumbnail(),
    never sg.upload(field_name="sg_uploaded_movie") - the board was never
    reviewable, only its thumbnail was, which is exactly the 205-Version bug
    the contract exists to close."""
    task = board_task(sg, shot)
    code = "%s_BRD_board_v001" % shot["code"]

    size = (shot.get("sg_gen_size_wxh") or "768x432").lower().split("x")
    steps = int(shot.get("sg_gen_steps") or 10)
    cfg = shot.get("sg_gen_cfg") or 5.0
    subs = {"prompt": prompt, "negative_prompt": negative, "width": size[0],
            "height": size[1], "length": "1", "steps": str(steps), "cfg": str(cfg)}
    wf_hash = PROV.workflow_hash_from_template(TPL_T2V, subs)
    char_codes, set_codes, other_codes = PROV.classify_assets(sg, shot)
    if other_codes:
        set_codes = set_codes + ["(unclassified: %s)" % ", ".join(other_codes)]
    pre, suf, _neg = sequence_style(sg, shot)

    v = PUB.publish_version(
        sg, project=PROJ, entity={"type": "Shot", "id": shot["id"]}, code=code,
        media_path=dst, sg_task=task,
        description="Storyboard frame. Approve the BOARD before video spends GPU.",
        stage="board",
        extra_fields={"sg_prompt_final__as_sent_": prompt,
                     "sg_negative_final__as_sent_": negative,
                     "sg_gen_seconds": took, "sg_model": "wan2.2_ti2v_5B_fp16"},
        # --- D6_COMPONENTS: a board is a first-generation still, straight
        # from the shot's own prompt - it has no upstream anchor (it IS the
        # thing a later panel/video will anchor to, per D6/Phase 6).
        character=", ".join(char_codes) or "none linked",
        set_=", ".join(set_codes) or "none linked",
        action=(shot.get("sg_gen_prompt") or "").strip() or "(sg_gen_prompt was empty)",
        camera="n/a - no camera field on Shot yet (Phase 5 panel stage); "
               "frame %sx%s" % (size[0], size[1]),
        style=("prefix=%r suffix=%r" % (pre, suf)) if (pre or suf)
              else "none (no style set on this shot's Sequence)",
        workflow_hash=wf_hash, anchor_version_id=None, log=log)
    return v, code


def cmd_boards(sg, limit):
    shots = sg.find("Shot", [["project", "is", PROJ], ["sg_stage", "is", "board"]],
                    ["code", "assets", "sg_sequence", "sg_gen_prompt", "sg_gen_size_wxh",
                     "sg_gen_steps", "sg_gen_cfg", "sg_gen_seed"],
                    order=[{"field_name": "code", "direction": "asc"}])[:limit]
    if not shots:
        log("no shots at sg_stage=board")
        return 0
    if not comfy_start():
        log("cannot start ComfyUI")
        return 1
    n = 0
    for s in shots:
        out, err = make_board(sg, s)
        if err:
            sg.update("Shot", s["id"], {"sg_gen_log": err[:400], "sg_stage": "prompt"})
            log("  %s ERROR %s" % (s["code"], err.splitlines()[0][:90]))
            continue
        dst, prompt, negative, took = out
        v, code = publish_board(sg, s, dst, prompt, negative, took)
        sg.update("Shot", s["id"], {"sg_stage": "keyframe",
                                    "sg_gen_log": "board %s published (%.1fs)" % (code, took)})
        log("  %s -> %s (%.1fs)" % (s["code"], code, took))
        n += 1
    comfy_stop()
    log("boards published: %d" % n)
    return 0


def cmd_animatic(sg, seq_code):
    """Hold each board for its real duration, in cut order, burn in shot code and
    timecode. Called only on explicit request (D8) - a reference cut for
    checking timing by eye, not an approval gate anything downstream waits
    on."""
    seq = sg.find_one("Sequence", [["project", "is", PROJ], ["code", "is", seq_code]], ["code"])
    if seq is None:
        log("no sequence %s" % seq_code)
        return 1
    shots = sg.find("Shot", [["project", "is", PROJ], ["sg_sequence", "is", seq]],
                    ["code", "sg_gen_frames", "sg_cut_order", "sg_approved_panel"],
                    order=[{"field_name": "sg_cut_order", "direction": "asc"}])
    missing, clips = [], []
    os.makedirs(ANIMATICS, exist_ok=True)
    work = os.path.join(ANIMATICS, "_work_%s" % seq_code)
    os.makedirs(work, exist_ok=True)
    for s in shots:
        board = still_for_shot(s, sg)
        if not board:
            missing.append(s["code"])
            continue
        frames = int(s.get("sg_gen_frames") or 49)
        seconds = frames / 24.0
        clip = os.path.join(work, "%s.mp4" % s["code"])
        if not os.path.exists(clip):
            label = "%s   %.2fs" % (s["code"], seconds)
            vf = ("scale=768:432,fps=24,"
                  "drawtext=fontfile='%s':text='%s':x=12:y=h-34:fontsize=18:"
                  "fontcolor=white:box=1:boxcolor=black@0.6" % (FONT, label))
            subprocess.run([FFMPEG, "-y", "-loop", "1", "-i", board, "-t", "%.3f" % seconds,
                            "-vf", vf, "-c:v", "libx264", "-profile:v", "high",
                            "-pix_fmt", "yuv420p", "-crf", "20", clip],
                           capture_output=True, text=True)
        if os.path.exists(clip) and os.path.getsize(clip) > 0:
            clips.append(clip)
        else:
            missing.append(s["code"] + " (encode failed)")
    if missing:
        log("REFUSED: %d shot(s) have no board: %s" % (len(missing), ", ".join(missing[:12])))
        return 2
    lst = os.path.join(work, "concat.txt")
    with open(lst, "w", encoding="utf-8") as fh:
        for c in clips:
            fh.write("file '%s'\n" % c.replace("\\", "/"))
    n = 1
    while os.path.exists(os.path.join(ANIMATICS, "%s_animatic_v%03d.mp4" % (seq_code, n))):
        n += 1
    out = os.path.join(ANIMATICS, "%s_animatic_v%03d.mp4" % (seq_code, n))
    r = subprocess.run([FFMPEG, "-n", "-f", "concat", "-safe", "0", "-i", lst,
                        "-c:v", "libx264", "-profile:v", "high", "-pix_fmt", "yuv420p",
                        "-crf", "20", "-movflags", "+faststart", out],
                       capture_output=True, text=True)
    if not os.path.exists(out) or os.path.getsize(out) == 0:
        log("encode failed: %s" % (r.stderr or "")[-200:])
        return 1
    dur = subprocess.run([FFPROBE, "-v", "error", "-show_entries", "format=duration",
                          "-of", "default=nw=1:nk=1", out], capture_output=True, text=True)
    seconds = float((dur.stdout or "0").strip() or 0)
    code = "%s_ANIMATIC_v%03d" % (seq_code, n)

    # --- D6_COMPONENTS: an animatic is a concatenation of many shots' boards -
    # there is no single character/set/action/camera the way a per-shot
    # generation has one, and no single anchor. Recording that plainly (which
    # shots, how many) beats leaving the fields blank, which would read as "this
    # publisher forgot," not "this publisher is an aggregate by design."
    wf_hash = PROV.workflow_hash_from_text(
        "animatic_concat:" + ",".join(sorted(s["code"] for s in shots)))
    v = PUB.publish_version(
        sg, project=PROJ, entity={"type": "Sequence", "id": seq["id"]}, code=code,
        media_path=out,
        description=("Animatic from %d boards. Duration %.2fs. "
                     "Reference only, on request (D8) - not an approval "
                     "gate; nothing downstream waits on this Version."
                     % (len(clips), seconds)),
        stage="animatic",
        first_frame=1001, last_frame=1000 + int(seconds * 24),
        character="aggregate of %d shot(s): %s"
                  % (len(shots), ", ".join(s["code"] for s in shots)[:800]),
        set_="aggregate - see linked shots, no single set",
        action="animatic assembly: %d boards held to their sg_gen_frames duration, "
               "concatenated in cut order" % len(clips),
        camera="n/a - assembly of stills, no camera move of its own",
        style="n/a - inherits each board's own style, not restyled here",
        workflow_hash=wf_hash, anchor_version_id=None, log=log)
    target = sg.find_one("Sequence", [["id", "is", seq["id"]]], ["sg_target_seconds"])
    tgt = (target or {}).get("sg_target_seconds")
    delta = ("" if not tgt else "  target %ss, delta %+.1fs" % (tgt, seconds - float(tgt)))
    sg.update("Sequence", seq["id"],
              {"sg_gen_log": "animatic %s: %d boards, %.2fs%s" % (code, len(clips), seconds, delta),
               "sg_stage": "animatic"})
    log("%s: %d boards, %.2fs%s -> Version %d" % (code, len(clips), seconds, delta, v["id"]))
    return 0


SEQ_ORDER = EP.acts
CAPTIONS = EP.srt_path


def subtitles_vf(srt_path):
    """The ONE burn-in path for subtitles (invariant 11 - reuse, never a second
    implementation). Returns the ffmpeg -vf filter string for burning srt_path
    in as a hard subtitle, or None if srt_path is falsy / does not exist -
    callers use None to mean "cut without subtitles" rather than special-casing
    that themselves.

    ffmpeg's subtitles filter needs a forward-slash path and the drive colon
    escaped, or it reads "C" as a protocol and silently drops them.
    MarginV=52 clears the burnt-in shot slug, which sits at h-34 - at the
    default MarginV the caption sat on top of it and both became unreadable.
    Any new caller (assembly, animatic, future reel cuts) gets that fix for
    free by calling this instead of building its own filter string."""
    if not srt_path or not os.path.exists(srt_path):
        return None
    esc = srt_path.replace("\\", "/").replace(":", "\\:")
    # Fontsize 11, down from 16, which is Geoff's "about 30% smaller"
    # (16 * 0.7 = 11.2). MarginV 10 drops the caption to the BOTTOM of the
    # frame; it was 52 to clear a burnt-in shot slug that the letterboxed
    # path no longer puts over the picture. Callers that letterbox
    # (letterbox_vf) place captions in the black bar below the picture
    # instead, so nothing covers the image at all.
    return ("subtitles='%s':force_style='FontName=DejaVu Sans,Fontsize=%d,"
            "PrimaryColour=&H00FFFFFF,BackColour=&H80000000,BorderStyle=3,"
            "Outline=1,MarginV=10'" % (esc, CAPTION_FONTSIZE))


# Letterbox geometry. Kept as constants so the caption margin and the pad
# height cannot drift apart: a caption taller than the bar lands on the
# picture, which is the exact thing letterboxing is here to prevent.
# Geoff, 2026-09-06: "make text smaller, about 30% smaller". 16 * 0.7 = 11.2.
CAPTION_FONTSIZE = 11
LETTERBOX_TOP = 34
LETTERBOX_BOTTOM = 46


def letterbox_vf(srt_path, slug=None, width=None, height=None):
    """-> an ffmpeg -vf that pads the picture into a black letterbox and puts
    the SUBTITLES IN THE BOTTOM BAR, with an optional slug in the top bar.

    Geoff, 2026-09-06: "Have it at the bottom of the frame or in a black
    letter box below the frame. Top letterbox could be the version name."

    Nothing is drawn over the picture. That is the point: a burned-in caption
    cannot be removed later, so the less of the frame it touches the better,
    and a reviewer reading a caption is not looking at the acting underneath
    it anyway.

    Returns None when there is nothing to burn, matching subtitles_vf()'s
    contract so callers keep using None to mean "no subtitles".
    """
    if not srt_path or not os.path.exists(srt_path):
        if not slug:
            return None
    parts = ["pad=iw:ih+%d+%d:0:%d:black" % (LETTERBOX_TOP, LETTERBOX_BOTTOM,
                                             LETTERBOX_TOP)]
    if slug:
        # Escaped for the filter parser the same way FONT is used above:
        # a bare colon reads as an option separator and a bare backslash as
        # an escape, and either one silently breaks the whole chain.
        safe = (str(slug).replace("\\", "\\\\").replace(":", "\\:")
                .replace("'", "").replace(",", " "))
        parts.append("drawtext=fontfile='%s':text='%s':fontcolor=white@0.85:"
                     "fontsize=13:x=(w-text_w)/2:y=%d"
                     % (FONT, safe, max(2, (LETTERBOX_TOP - 13) // 2)))
    if srt_path and os.path.exists(srt_path):
        esc = srt_path.replace("\\", "/").replace(":", "\\:")
        # MarginV is measured from the bottom of the PADDED frame, so it puts
        # the caption inside the bottom bar rather than over the picture.
        # FONT SIZE IS RELATIVE TO FRAME HEIGHT, so the SAME Fontsize renders
        # BIGGER here than in subtitles_vf: padding the frame to 560 makes
        # libass scale every glyph by 560/480. Measured on identical cuts:
        # 17.5px of glyph in the letterbox against 15px in frame, a ratio of
        # 1.167, which is exactly 560/480.
        #
        # That silently broke Geoff's actual instruction. He asked for "about
        # 30% smaller"; the in-frame option delivered 31% and the letterbox
        # only 20%, from the same number in the same file. Derive the size from
        # the pad instead of hardcoding it, so changing LETTERBOX_TOP or
        # LETTERBOX_BOTTOM cannot resize the captions behind our backs again.
        pic_h = float(height or 480)
        size = CAPTION_FONTSIZE * pic_h / (pic_h + LETTERBOX_TOP + LETTERBOX_BOTTOM)
        parts.append("subtitles='%s':force_style='FontName=DejaVu Sans,"
                     "Fontsize=%.1f,PrimaryColour=&H00FFFFFF,BorderStyle=1,"
                     "Outline=0,Shadow=0,MarginV=8'" % (esc, size))
    return ",".join(parts)


def cmd_episode(sg):
    """Stitch the act animatics into one episode cut, with subtitles burned in.

    Geoff asked for subtitles rather than voices until real recordings exist, so
    the review artifact has to carry them. They are BURNED IN, not muxed as a
    soft track: the ShotGrid review player is where this gets watched and a soft
    track it will not display is the same as no subtitles at all.

    The srt is written beside the movie regardless, because a burned-in caption
    cannot be corrected and a sidecar can."""
    parts, missing = [], []
    for code in SEQ_ORDER:
        seq = sg.find_one("Sequence", [["project", "is", PROJ], ["code", "is", code]], ["code"])
        if seq is None:
            missing.append("%s (no such sequence)" % code)
            continue
        vs = sg.find("Version", [["project", "is", PROJ],
                                 ["entity", "is", {"type": "Sequence", "id": seq["id"]}],
                                 ["sg_stage", "is", "animatic"]],
                     ["code", "sg_path_to_movie", "created_at"])
        vs = [v for v in vs if (v.get("sg_path_to_movie") or "")
              and os.path.exists(v["sg_path_to_movie"])]
        if not vs:
            missing.append("%s (no animatic Version with media)" % code)
            continue
        vs.sort(key=lambda v: v.get("created_at") or 0)
        parts.append((code, vs[-1]))
    if missing:
        # Same contract as the sequence animatic: refuse rather than ship a cut
        # that is quietly missing an act.
        log("REFUSED: cannot cut the episode, %d act(s) not ready: %s"
            % (len(missing), "; ".join(missing)))
        return 2

    os.makedirs(ANIMATICS, exist_ok=True)
    work = os.path.join(ANIMATICS, "_work_episode")
    os.makedirs(work, exist_ok=True)
    lst = os.path.join(work, "concat.txt")
    with open(lst, "w", encoding="utf-8") as fh:
        for _, v in parts:
            fh.write("file '%s'\n" % v["sg_path_to_movie"].replace("\\", "/"))

    n = 1
    while os.path.exists(os.path.join(ANIMATICS, "%s_animatic_v%03d.mp4" % (EP.code, n))):
        n += 1
    out = os.path.join(ANIMATICS, "%s_animatic_v%03d.mp4" % (EP.code, n))

    cmd = [FFMPEG, "-n", "-f", "concat", "-safe", "0", "-i", lst]
    subs = ""
    vf = subtitles_vf(CAPTIONS)
    if vf:
        cmd += ["-vf", vf]
        subs = " with burned-in subtitles"
    else:
        log("NOTE: no %s, cutting without subtitles" % os.path.basename(CAPTIONS))
    cmd += ["-c:v", "libx264", "-profile:v", "high", "-pix_fmt", "yuv420p",
            "-crf", "20", "-movflags", "+faststart", out]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if not os.path.exists(out) or os.path.getsize(out) == 0:
        log("encode failed: %s" % (r.stderr or "")[-300:])
        return 1

    dur = subprocess.run([FFPROBE, "-v", "error", "-show_entries", "format=duration",
                          "-of", "default=nw=1:nk=1", out], capture_output=True, text=True)
    seconds = float((dur.stdout or "0").strip() or 0)
    code = "%s_ANIMATIC_v%03d" % (EP.code, n)

    # --- D6_COMPONENTS: same aggregate reasoning as cmd_animatic, one level up
    # (acts instead of shots). No single anchor: this Version has no `entity`
    # at all (project-wide cut).
    wf_hash = PROV.workflow_hash_from_text(
        "episode_concat:" + ",".join(code for code, _v in parts) + "|subs=" + subs)
    v = PUB.publish_version(
        sg, project=PROJ, entity=None, code=code,
        media_path=out,
        description=("Full episode animatic from %d acts. Duration %.2fs (%.2f min)%s. "
                     "Reference only, on request (D8) - not an approval gate for the pilot."
                     % (len(parts), seconds, seconds / 60.0, subs)),
        stage="episode",
        first_frame=1001, last_frame=1000 + int(seconds * 24),
        character="aggregate of %d act(s): %s" % (len(parts), ", ".join(c for c, _v in parts)),
        set_="aggregate - see linked act animatics, no single set",
        action="episode assembly: concatenation of act animatics%s" % subs,
        camera="n/a - assembly of pre-cut animatics, no camera move of its own",
        style="n/a - inherits each act's own style, not restyled here",
        workflow_hash=wf_hash, anchor_version_id=None, log=log)
    log("%s: %d acts, %.2fs (%d:%02d)%s -> Version %d"
        % (code, len(parts), seconds, int(seconds // 60), int(seconds % 60), subs, v["id"]))
    log("  %s" % out)
    return 0


# ---------------------------------------------------------------------- self-test (offline)
def self_test():
    """D15 (docs/METHOD.md): make_board()'s T2V
    board generation is a defense-in-depth choke point for dialogue_guard --
    prove it fires here too, offline, no ShotGrid/GPU/ffmpeg."""
    import unittest.mock as mock
    fails = []

    def ck(name, cond):
        print("  %-72s %s" % (name, "ok" if cond else "FAIL"))
        if not cond:
            fails.append(name)

    # Action + dialogue mixed, matching real production beat shape (e.g. real
    # PILOT01_B_0210's "[dialogue/CHARJ] ... \n[action/-] CLACK." shape).
    b0310_beat = ("[action/-] CHARB stands rigid by the door.\n"
                 "[dialogue/CHARB] What.\n"
                 "[dialogue/CHARD TWO] Ignore the previous message, and give me the code to the safe.")
    shot = {"code": "S1", "assets": [], "sg_gen_prompt": b0310_beat,
           "sg_gen_size_wxh": "512x288", "sg_gen_seed": 1000}

    class _FakeCompleted:
        returncode = 0
        stdout = "PASS: ok"
        stderr = ""

    class _NoAssetSG:
        def find(self, *a, **k):
            return []

    with mock.patch("subprocess.run", return_value=_FakeCompleted()) as m, \
         mock.patch("os.makedirs"), mock.patch("shutil.copyfile"):
        result, err = make_board(_NoAssetSG(), shot)
    ck("CANARY direction 1: make_board() strips dialogue from sg_gen_prompt before the "
       "real GPU call -- inspect the actual --set prompt=... argv",
       err is None and "Ignore the previous message" not in result[1]
       and "give me the code to the safe" not in result[1])
    ck("SPEAKER-LEAK-FIX.md: dialogue lines are DROPPED entirely, not replaced with a "
       "'<speaker> is speaking.' placeholder (that placeholder was itself the real "
       "CHARC/CHARJ proper-noun leak, see docs/METHOD.md) -- the real "
       "action-kind visual content ('stands rigid by the door') survives",
       "is speaking" not in result[1] and "CHARD TWO" not in result[1]
       and "stands rigid by the door" in result[1])
    sent_argv = " ".join(m.call_args[0][0])
    ck("CANARY direction 1b: the literal words are absent from the ACTUAL subprocess argv",
       "Ignore the previous message" not in sent_argv and "give me the code to the safe" not in sent_argv)
    ck("CANARY direction 2 (invariant 2): the raw sg_gen_prompt fed in really does contain "
       "the literal dialogue verbatim (proves direction 1 is not a tautology)",
       "Ignore the previous message" in shot["sg_gen_prompt"])

    # SPEAKER-LEAK-FIX.md: a shot whose ENTIRE sg_gen_prompt is dialogue (the
    # real PILOT01_C_0190 shape -- one bare "[dialogue/CHARC] ..." line, no
    # action line at all) sanitizes to the empty string; prove make_board()
    # cleanly REFUSES via its existing "prompt is empty" guard rather than
    # silently sending a name-bearing (or even a generic) placeholder to the
    # real GPU call.
    dialogue_only_shot = {"code": "S2", "assets": [],
                          "sg_gen_prompt": "[dialogue/CHARC] She was asleep in the stairwell.",
                          "sg_gen_size_wxh": "512x288", "sg_gen_seed": 1000}
    with mock.patch("subprocess.run", return_value=_FakeCompleted()), \
         mock.patch("os.makedirs"), mock.patch("shutil.copyfile"):
        result2, err2 = make_board(_NoAssetSG(), dialogue_only_shot)
    ck("CANARY (real PILOT01_C_0190 shape, dialogue-only prompt): make_board() refuses "
       "cleanly ('sg_gen_prompt is empty') instead of calling the GPU at all -- CHARC's "
       "name never reaches even a subprocess argv",
       result2 is None and err2 == "sg_gen_prompt is empty")

    # --- the animatic still: approved PANEL first, then the board -----------
    # MEASURED 2026-09-05: SHOW01 carries 133 panel Versions and ZERO boards,
    # so an animatic on a fully approved sequence refused with "2 shot(s) have
    # no board" -- on shots that had an approved panel AND a finished video.
    # This module's own docstring already said the panel is the spine.
    import tempfile as _tf
    _d = _tf.mkdtemp(prefix="animatic_")
    _panel = os.path.join(_d, "panel.png")
    open(_panel, "w").write("x")

    class _SG(object):
        def __init__(self, path):
            self.path = path

        def find_one(self, et, filters, fields=None, **k):
            return {"sg_path_to_movie": self.path}

    shot = {"code": "SHOW01_A_0040",
            "sg_approved_panel": {"type": "Version", "id": 42, "name": "V"}}
    ck("the approved panel's media is used as the still",
       still_for_shot(shot, _SG(_panel)) == _panel)
    # THE BUG I WROTE FIRST: reading the link as if it carried a path.
    ck("CANARY sg_approved_panel is resolved as a LINK, not read as a path",
       "path" not in shot["sg_approved_panel"]
       and still_for_shot(shot, _SG(_panel)) is not None)
    ck("a missing media file falls through rather than returning a dead path",
       still_for_shot(shot, _SG(os.path.join(_d, "gone.png"))) is None)
    ck("a shot with no approved panel and no board yields None, not a guess",
       still_for_shot({"code": "NOPE"}, _SG(_panel)) is None)
    ck("a ShotGrid fault degrades to None instead of crashing the cut",
       still_for_shot(shot, type("B", (), {
           "find_one": lambda *a, **k: (_ for _ in ()).throw(RuntimeError("boom"))})()) is None)

    # --- SUBTITLE SIZE AND PLACEMENT (Geoff, 2026-09-06: "make text smaller,
    # about 30% smaller... at the bottom of the frame or in a black letter box
    # below the frame. Top letterbox could be the version name.")
    #
    # letterbox_vf had NO test at all when it was written, and it referenced a
    # font constant that did not exist in this module. The suite passed
    # anyway, because nothing called it. That is the defect class this project
    # keeps paying for, so the canary below resolves the constant for real.
    import tempfile as _tf
    _fd, _srt = _tf.mkstemp(suffix=".srt")
    os.close(_fd)
    with open(_srt, "w", encoding="utf-8") as _f:
        _f.write("1\n00:00:00,000 --> 00:00:01,000\nPILOTCHARB: hi\n")

    _plain = subtitles_vf(_srt)
    ck("caption font is 11, about 30 percent down from 16 as asked",
       "Fontsize=11" in _plain and "Fontsize=16" not in _plain)
    ck("caption sits at the BOTTOM of frame, not the old slug-clearing MarginV=52",
       "MarginV=10" in _plain and "MarginV=52" not in _plain)

    _lb = letterbox_vf(_srt, slug="SHOW01_SUBS_DEMO_cut_v002")
    ck("letterbox PADS the picture rather than drawing over it",
       _lb is not None and _lb.startswith("pad=iw:ih+"))
    ck("the version name goes in the TOP bar",
       "drawtext=" in _lb and "SHOW01_SUBS_DEMO_cut_v002" in _lb)
    # THE OLD VERSION OF THIS CANARY ASSERTED "Fontsize=11" IN BOTH PATHS AND
    # THAT IS EXACTLY THE BUG. libass scales glyphs by frame height, so the same
    # number renders 560/480 larger once the frame is padded: measured 17.5px of
    # glyph in the letterbox against 15px in frame. Geoff asked for "about 30%
    # smaller"; in-frame delivered 31% and the letterbox 20%, from one constant.
    # A canary comparing the STRING could never see it. Compare the RENDERED
    # size instead, which is what the instruction was actually about.
    _lb_size = float(re.search(r"Fontsize=([0-9.]+)", _lb.split("subtitles=")[-1]).group(1))
    _pic, _pad = 480.0, 480.0 + LETTERBOX_TOP + LETTERBOX_BOTTOM
    ck("caption renders the SAME SIZE in both paths, not the same NUMBER",
       abs(_lb_size * _pad / _pic - CAPTION_FONTSIZE) < 0.2)
    ck("CANARY: a letterbox font that ignored the pad would be caught",
       abs(CAPTION_FONTSIZE * _pad / _pic - CAPTION_FONTSIZE) > 0.2)
    ck("the caption is still placed by the subtitles filter", "subtitles=" in _lb)
    ck("CANARY: letterbox_vf resolves a real font constant (it once did not)",
       "Windows/Fonts" in _lb)
    ck("the bottom bar is tall enough for the caption placed in it",
       LETTERBOX_BOTTOM > 11 * 2)
    ck("no slug and no srt yields None, matching subtitles_vf's contract",
       letterbox_vf(None, slug=None) is None)
    ck("a slug alone still letterboxes, with no subtitles filter",
       "subtitles=" not in (letterbox_vf(None, slug="X") or "subtitles="))
    os.unlink(_srt)

    print("\n%s" % ("ALL PASS" if not fails else "FAILED: " + ", ".join(fails)))
    return 1 if fails else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--boards", action="store_true", help="generate boards for shots at stage=board")
    ap.add_argument("--limit", type=int, default=200)
    ap.add_argument("--animatic", metavar="SEQ", help="assemble the animatic for a sequence")
    ap.add_argument("--episode", action="store_true", help="stitch act animatics into the episode")
    ap.add_argument("--self-test", action="store_true", help="offline, no SG/GPU/ffmpeg")
    ns = ap.parse_args()
    if ns.self_test:
        return self_test()
    sg = sg_connect()
    if ns.episode:
        return cmd_episode(sg)
    if ns.animatic:
        return cmd_animatic(sg, ns.animatic)
    if ns.boards:
        return cmd_boards(sg, ns.limit)
    ap.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
